In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load r14_data into DataFrame
r14_data = pd.read_csv(r'C:\Users\KATAKOF\Downloads\T24 DRESS REHEARSAL 3\REVISED FILES\R14_Customer.txt',delimiter = "|", low_memory=False,dtype = "object")
# r22_data = r22_data.rename(columns={r22_data.columns[0]: identifier})

In [4]:
# Load r14_data into DataFrame
r14_data = pd.read_csv(r'C:\Users\KATAKOF\Downloads\T24 DRESS REHEARSAL 2\R14\FINANCIAL\R14 _DR2.MD.DEAL.202300706.txt',delimiter = "|", low_memory=False,dtype = "object")
# r22_data = r22_data.rename(columns={r22_data.columns[0]: identifier})

In [5]:
# Load r22_data into DataFrame
r22_data = pd.read_csv(r'C:\Users\KATAKOF\Downloads\T24 DRESS REHEARSAL 2\R22\MD.DEAL.EXT.csv',delimiter = "|",dtype = "object", low_memory=False)

In [6]:
# Load r14_data and r22_data into DataFrames
# r14_data = pd.read_csv(r'C:\Users\KATAKOF\Downloads\T24 DRESS REHEARSAL\R14\R14 _DR.INDV.CUSTOMER.20230601.txt', low_memory=False, delimiter = "|")
# r22_data = pd.read_csv(r'C:\Users\KATAKOF\Downloads\T24 Reconciliation\DM3\R22\Test\R22_DM3 ACCT CAP.csv', low_memory=False)
# r22_data = r22_data.rename(columns={r22_data.columns[0]: identifier})

In [7]:
# r22_data = pd.read_excel(r'C:\Users\KATAKOF\Downloads\ACCOUNTS TO BE REMOVED.xlsx')

In [3]:
r14_data.head()

,UPLOAD_COMPANY,@ID,MNEMONIC,SHORT_NAME,NAME_1,NAME_2,STREET,TOWN_COUNTRY,SECTOR,ACCOUNT_OFFICER,...,PCUS_CARD_PURP,PCUS_DEP_FREQ,PCUS_DISABILITY,PCUS_EXP_LOAD,PCUS_F_SOURCE,PCUS_P_OF_BIRTH,PCUS_PRF_SOURCE,DETAILS_CHECK,REFER_INFLOW,GHA_CARD
0,GH0010001,264107,UM00264107,OSAFO NANA ADOMAKO,OSAFO NANA ADOMAKO,NaN,P O BOX 227 KOFORIDUA,NaN,9000,120435,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,GH0010001,264133,UM00264133,DIALLO SALIOU MAMADOU,DIALLO SALIOU MAMADOU,NaN,P O BOX 7516 ACCRA,NaN,9000,120435,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,GH0010001,264137,UM00264137,MALLAVARAPU JOSEPH ANIL KUMAR,MALLAVARAPU JOSEPH ANIL KUMAR,NaN,P O BOX 38 CHURCH CRESCENTS IPMC CO,LLEGE OF TECHNOLOGY LABONE,9000,120435,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,GH0010001,264553,UM00264553,DANKYI DANIEL BOATENG,DANKYI DANIEL BOATENG,NaN,P O BOX MP16 MAMOBI,NaN,9000,108715,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GH0010001,264559,UM00264559,AFUM EMMANUEL,AFUM EMMANUEL,NaN,P O BOX 27 AKIM ODA,NaN,9000,120686,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# columns_to_merge = r14_data.columns

In [10]:
# r14_data['Merged_Column'] = r14_data[columns_to_merge].apply(lambda x: '|'.join(x.dropna().astype(str)), axis=1)

In [11]:
r22_data.head()

,@ID,DEAL_NO,CUSTOMER,CURRENCY,CCY_MARKET,PRINCIPAL_AMOUNT,DEAL_DATE,VALUE_DATE,MATURITY_DATE,CONTRACT_TYPE,...,FX_PERMIT_NUMBE,PO_PERMIT_NUMBE,INPUT_VERSION,BRANCH,MD_SECTOR,MD_INDUSTRY,APPL_VERSION,LC_USD_AMT,CROSS_RATE,CAMB_CA_INTED
0,MD2002401039,MD2002401039,37827,USD,1,2601792.17,20200108,20200108,20230915,CA,...,NaN,NaN,NaN,GH0010010,7000,7002,NaN,14960304.98,5.75,NaN
1,MD2130901320,MD2130901320,308973,GHS,1,1406012.09,20201104,20201104,20241231,CA,...,NaN,NaN,NaN,GH0010024,7000,7002,NaN,2656460.70,1,NaN
2,MD2130901322,MD2130901322,330228,GHS,1,1278081.85,20201104,20201104,20241231,CA,...,NaN,NaN,NaN,GH0010004,7000,7002,NaN,1779129.07,1,NaN
3,MD2130901325,MD2130901325,310682,GHS,1,2899330.43,20201104,20201104,20241231,CA,...,NaN,NaN,NaN,GH0010024,7000,7002,NaN,3760663.13,1,NaN
4,MD2130901326,MD2130901326,313458,GHS,1,3104225.04,20201104,20201104,20241231,CA,...,NaN,NaN,NaN,GH0010024,7000,7002,NaN,3104225.04,1,NaN

In [2]:
# Only run when r22_data contains CO:CODE
# r22_data = r22_data.rename(columns = {"CO_CODE" : "UPLOAD_COMPANY"})

In [8]:
r22_data.columns

Index(['@ID', 'ACCOUNT_NUMBER', 'CUSTOMER', 'CATEGORY', 'PRODCAT',
       'ACCOUNT_TITLE_1', 'ACCOUNT_TITLE_2', 'SHORT_TITLE', 'MNEMONIC',
       'POSITION_TYPE',
       ...
       'AML_ID_AUTH', 'AML_ID_SDATE', 'AML_ID_EDATE', 'AML_PHONE_NO',
       'AML_EMP_NAME', 'SAL_IND', 'SALARY_COMP', 'BULK_SOURCE_ACC',
       'DETAILS_CHECK', 'COMPLETION_DATE'],
      dtype='object', length=222)

In [9]:
# r22_data = r22_data.rename(columns= {"ALT_ACCT_ID":identifier})

In [28]:
r14_data.dtypes

@ID                object
UPLOAD_COMPANY     object
MNEMONIC           object
SHORT_NAME         object
NAME_1             object
                    ...
PCUS_P_OF_BIRTH    object
PCUS_PRF_SOURCE    object
DETAILS_CHECK      object
REFER_INFLOW       object
GHA_CARD           object
Length: 307, dtype: object

In [22]:
# Define the identifier column
identifier = "@ID"
# r22_data = r22_data.rename(columns={r22_data.columns[0]: identifier})
# r22_data.head()

In [23]:
# r22_data["CUSTOMER_NO"] = r22_data["CUSTOMER_NO"].astype("float")

In [24]:
# float_columnsr14 = r14_data.select_dtypes(include='float')
# float_columnsr22 = r22_data.select_dtypes(include='float')
# float_columns_listr14 = float_columnsr14.columns.tolist()
# float_columns_listr22 = float_columnsr22.columns.tolist()

In [25]:
# not_in_list_b = list(set(float_columns_listr22) - set(float_columns_listr14))
# not_in_list_b

In [26]:
# Iterate over the columns in r14
# for column in r14_data.columns:
#     # Check if the column exists in r22
#     if column in r22_data.columns:
#         type_r14_data = r14_data[column].dtypes
#         type_r22_data = r22_data[column].dtypes

#         # Check if column data types are different
#         if type_r14_data != type_r22_data:
#             # Change the column type of r22 to match r14
#             r22_data[column] = r14_data[column].astype(type_r14_data)
#     else:
#         # Skip the column if it doesn't exist in r22
#         continue

In [27]:
def trim_string_columns(data):
    if isinstance(data, pd.DataFrame):
        string_columns = data.select_dtypes(include='object').columns
        data[string_columns] = data[string_columns].apply(lambda x: x.str.strip())
    return data

# Trim columns first in r_14 dataset
r14_columns_trimmed = trim_string_columns(r14_data)

In [28]:
# Trim string columns in r_14 dataset
r22_columns_trimmed = trim_string_columns(r22_data)

In [29]:
# Extract common observations based on "@ID" column
common_rows = pd.merge(r14_columns_trimmed, r22_columns_trimmed, on= identifier, how="inner")

# Extract column names that are common between the datasets
common_columns = r14_data.columns.intersection(r22_data.columns)

In [30]:
common_rows.head()

,UPLOAD_COMPANY_x,@ID,CUSTOMER_x,CURRENCY_x,CCY_MARKET_x,PRINCIPAL_AMOUNT_x,DEAL_DATE_x,VALUE_DATE_x,MATURITY_DATE_x,CONTRACT_TYPE_x,...,FX_PERMIT_NUMBE,PO_PERMIT_NUMBE,INPUT_VERSION,BRANCH_y,MD_SECTOR_y,MD_INDUSTRY_y,APPL_VERSION_y,LC_USD_AMT_y,CROSS_RATE_y,CAMB_CA_INTED
0,GH0010001,MD2219601468,515703,GHS,1,600000.00,20220713,20220713,20231017,CA,...,NaN,NaN,NaN,GH0010036,7000,7002,NaN,600000.00,1,NaN
1,GH0010001,MD2130901320,308973,GHS,1,1406012.09,20201104,20201104,20241231,CA,...,NaN,NaN,NaN,GH0010024,7000,7002,NaN,2656460.70,1,NaN
2,GH0010001,MD2233401509,6243,GHS,1,10000000.00,20220930,20220930,20230930,CA,...,NaN,NaN,NaN,GH0010006,7000,7002,NaN,10000000.00,1,NaN
3,GH0010001,MD2234601523,7239,USD,1,2000000.00,20221212,20221212,20231212,CA,...,NaN,NaN,NaN,GH0010002,7000,7002,NaN,25116000.00,12.5580,NaN
4,GH0010001,MD2233401508,6243,GHS,1,10000000.00,20220930,20220930,20230930,CA,...,NaN,NaN,NaN,GH0010006,7000,7002,NaN,10000000.00,1,NaN

In [31]:
common_columns = list(set(r14_columns_trimmed.columns) & set(r22_columns_trimmed.columns))
# common_columns.append(identifier)

In [32]:
# Define the columns to be merged
columns_to_merge = list(common_columns)

# columns_to_merge

In [33]:
# Convert NaN values to blank values
common_rows = common_rows.fillna("")
common_rows
# # Drop columns that don't end with "_x" or "_y" and aren't equal to "@ID"
# columns_to_drop = [col for col in common_rows.columns if not col.endswith(("_x", "_y")) and col != "@ID"]
# common_rows = common_rows.drop(columns_to_drop, axis=1)

,UPLOAD_COMPANY_x,@ID,CUSTOMER_x,CURRENCY_x,CCY_MARKET_x,PRINCIPAL_AMOUNT_x,DEAL_DATE_x,VALUE_DATE_x,MATURITY_DATE_x,CONTRACT_TYPE_x,...,FX_PERMIT_NUMBE,PO_PERMIT_NUMBE,INPUT_VERSION,BRANCH_y,MD_SECTOR_y,MD_INDUSTRY_y,APPL_VERSION_y,LC_USD_AMT_y,CROSS_RATE_y,CAMB_CA_INTED
0,GH0010001,MD2219601468,515703,GHS,1,600000.00,20220713,20220713,20231017,CA,...,,,,GH0010036,7000,7002,,600000.00,1,
1,GH0010001,MD2130901320,308973,GHS,1,1406012.09,20201104,20201104,20241231,CA,...,,,,GH0010024,7000,7002,,2656460.70,1,
2,GH0010001,MD2233401509,6243,GHS,1,10000000.00,20220930,20220930,20230930,CA,...,,,,GH0010006,7000,7002,,10000000.00,1,
3,GH0010001,MD2234601523,7239,USD,1,2000000.00,20221212,20221212,20231212,CA,...,,,,GH0010002,7000,7002,,25116000.00,12.5580,
4,GH0010001,MD2233401508,6243,GHS,1,10000000.00,20220930,20220930,20230930,CA,...,,,,GH0010006,7000,7002,,10000000.00,1,
5,GH0010001,MD2206301398,313458,GHS,1,504216.2,20220304,20220304,20241231,CA,...,,,,GH0010024,7000,7002,,1797928.37,1,
6,GH0010001,MD2318001562,891364,GHS,1,100000.00,20230613,20230613,20240612,CA,...,,,,GH0010009,7000,7002,,100000.00,1.000,
7,GH0010001,MD2130901325,310682,GHS,1,2899330.43,20201104,20201104,20241231,CA,...,,,,GH0010024,7000,7002,,3760663.13,1,
8,GH0010001,MD2233401513,6563,GHS,1,10000000.00,20220930,20220930,20230930,CA,...,,,,GH0010006,7000,7002,,10000000.00,1,
9,GH0010001,MD2233401512,6563,GHS,1,10000000.00,20220930,20220930,20230930,CA,...,,,,GH0010006,7000,7002,,10000000.00,1,
10,GH0010001,MD2134801345,330228,GHS,1,2930517.07,20210909,20210909,20241231,CA,...,,,,GH0010004,7000,7002,,3974000.00,1,
11,GH0010001,MD2224101476,909924,USD,1,4000000.00,20220809,20220809,20230831,CA,...,,,,GH0010024,7000,7002,,32902000.00,8.2255,
12,GH0010001,MD2234801525,524309,GHS,1,1200000.00,20221130,20221130,20231129,CA,...,,,,GH0010036,7000,7002,,1200000.00,1.000,
13,GH0010001,MD2233401515,877627,GHS,1,20000000.00,20220930,20220930,20230930,CA,...,,,,GH0010006,7000,7002,,20000000.00,1,
14,GH0010001,MD2317401559,33438,GHS,1,40886.00,20230529,20230529,20240528,CA,...,,,,GH0010009,7000,7002,,40886.00,1.000,
15,GH0010001,MD2232101485,346454,GHS,1,800000.00,20220930,20220930,20230930,CA,...,,,,GH0010026,7000,7002,,800000.00,1,
16,GH0010001,MD2318001564,891364,GHS,1,100000.00,20230613,20230613,20240612,CA,...,,,,GH0010009,7000,7002,,100000.00,1.000,
17,GH0010001,MD2232201488,406553,GHS,1,300000.00,20220922,20220922,20230922,CA,...,,,,GH0010005,7000,7002,,300000.00,1.000,
18,GH0010001,MD2206301397,313458,GHS,1,1526341.19,20220304,20220304,20241231,CA,...,,,,GH0010024,7000,7002,,3005157.73,1,
19,GH0010001,MD2233401502,7254,GHS,1,10000000.00,20220930,20220930,20230930,CA,...,,,,GH0010002,7000,7002,,10000000.00,1,
20,GH0010001,MD2308101549,892096,GHS,1,40000.00,20230307,20230307,20230707,CA,...,,,,GH0010028,7000,7002,,40000.00,1,
21,GH0010001,MD2233401514,877627,GHS,1,10000000.00,20220930,20220930,20230930,CA,...,,,,GH0010006,7000,7002,,10000000.00,1,
22,GH0010001,MD2232201487,431960,GHS,1,700000,20221117,20221117,20231117,CA,...,,,,GH0010029,7000,7002,,450000.00,1.000,
23,GH0010001,MD2233401516,877627,GHS,1,20000000.00,20220930,20220930,20230930,CA,...,,,,GH0010006,7000,7002,,20000000.00,1,
24,GH0010001,MD2317401560,125882,GHS,1,140000.00,20230512,20230512,20240511,CA,...,,,,GH0010005,7000,7002,,140000.00,1.000,
25,GH0010001,MD2233401495,6139,GHS,1,500000.00,20221108,20221108,20231108,CA,...,,,,GH0010002,7000,7002,,500000.00,1,
26,GH0010001,MD2219601470,512340,USD,1,6000000.00,20220715,20220715,20230715,CA,...,,,,GH0010024,7000,7004,,44127000.00,7.3545,
27,GH0010001,MD2233401503,7254,GHS,1,10000000.00,20220930,20220930,20230930,CA,...,,,,GH0010002,7000,7002,,10000000.00,1,
28,GH0010001,MD2002401039,37827,USD,1,2601792.17,20200108,20200108,20230915,CA,...,,,,GH0010010,7000,7002,,14960304.98,5.75,
29,GH0010001,MD2233401507,264195,USD,1,50000.00,20221109,20221109,20231109,CA,...,,,,GH0010027,7000,7002,,655230.00,13.1046,
30,GH0010001,MD2130901322,330228,GHS,1,1278081.85,20201104,20201104,20241231,CA,...,,,,GH0010004,7000,7002,,1779129.07,1,
31,GH0010001,MD2212601436,395800,GHS,1,3500973.64,20220427,20220427,20230928,CA,...,,,,GH0010024,7000,7002,,3500973.64,1,
32,GH0010001,MD2232201489,255467,GHS,1,1200000.00,20220815,20220815,20230815,CA,...,,,,GH0010003,7000,7002,,1200000.00,1.000,
33,GH0010001,MD2230601483,334011,GHS,1,1000000.00,20220822,20220822,20230923,CA,...,,,,GH0010003,7000,7002,,1000000.00,1,
34,GH0010001,MD2307901546,8062,GHS,1,200000.00,20221128,20221128,20231127,CA,...,,,,GH0010002,7000,7002,,200000.00,1,
35,GH0010001,MD2309001552,114857,GHS,1,2778000.00,20230401,20230401,20240331,CA,...,,,,GH0010020,7000,7002,,2778000.00,1.000,
36,GH0010001,MD2233501519,6563,GHS,1,10000000.00,20220930,20220930,20230930,CA,...,,,,GH0010002,7000,7002,,10000000.00,1,
37,GH0010001,MD2233401511,6563,GHS,1,10000000.00,20220930,20220930,20230930,CA,...,,,,GH0010006,7000,7002,,10000000.00,1,
38,GH0010001,MD2130901326,313458,GHS,1,3104225.04,20201104,20201104,20241231,CA,...,,,,GH0010024,7000,7002,,3104225.04,1,
39,GH0010001,MD2229201482,877563,USD,1,1220385.06,20221018,20221018,20231018,CA,...,,,,GH0010024,7000,7002,,13266683.95,10.8709,
40,GH0010001,MD2318001563,891364,GHS,1,100000.00,20230613,20230613,20240612,CA,...,,,,GH0010009,7000,7002,,100000.00,1.000,

In [34]:
# exclude_columns = ['a']

# # Iterate over columns and convert float to integer using np.where
# for column in common_rows.columns:
#     if column not in exclude_columns and common_rows[column].dtype == 'float64':
#         common_rows[column] = np.where(common_rows[column].notnull(), common_rows[column].astype(int), common_rows[column])

In [35]:
merged_columns = []

for column in columns_to_merge:
    column_x = f"{column}_x"
    column_y = f"{column}_y"

    try:
        merged_column = np.where(
            common_rows[column_x] != common_rows[column_y],
            np.where(
                (common_rows[column_x] != "") & (common_rows[column_y] != ""),
                common_rows[column_x].astype(str) + "|" + common_rows[column_y].astype(str),
                np.where(common_rows[column_x] == "", " |" + common_rows[column_y].astype(str), common_rows[column_x].astype(str))
            ),
            ""
        )

        # Append the merged column to the list
        merged_columns.append(pd.DataFrame(merged_column, columns=[f"{column}_z"]))

    except KeyError:
        continue

# Concatenate all merged columns at once
merged_columns_df = pd.concat([common_rows] + merged_columns, axis=1)

In [36]:
merged_columns_df

,UPLOAD_COMPANY_x,@ID,CUSTOMER_x,CURRENCY_x,CCY_MARKET_x,PRINCIPAL_AMOUNT_x,DEAL_DATE_x,VALUE_DATE_x,MATURITY_DATE_x,CONTRACT_TYPE_x,...,PROV_DR_ACCOUNT_z,SENDER_INFO_z,MATURITY_DATE_z,LINK_REFERENCE_z,CHARGE_AMT_z,ADVICE_EXPIRY_DATE_z,SL_PROD_TYPE_z,ACTIVITY_CODE_z,CONVERSION_RATE_z,CSN_DATE_z
0,GH0010001,MD2219601468,515703,GHS,1,600000.00,20220713,20220713,20231017,CA,...,,,,,,,,MD-2101|MD-1101,,
1,GH0010001,MD2130901320,308973,GHS,1,1406012.09,20201104,20201104,20241231,CA,...,,,,,,,,MD-2101|MD-1101,,
2,GH0010001,MD2233401509,6243,GHS,1,10000000.00,20220930,20220930,20230930,CA,...,,,,,,,,,,
3,GH0010001,MD2234601523,7239,USD,1,2000000.00,20221212,20221212,20231212,CA,...,,,,,,,,MD-2101|MD-1101,,
4,GH0010001,MD2233401508,6243,GHS,1,10000000.00,20220930,20220930,20230930,CA,...,,,,,,,,,,
5,GH0010001,MD2206301398,313458,GHS,1,504216.2,20220304,20220304,20241231,CA,...,,,,,,,,MD-2101|MD-1101,,
6,GH0010001,MD2318001562,891364,GHS,1,100000.00,20230613,20230613,20240612,CA,...,,,,,,,,,,
7,GH0010001,MD2130901325,310682,GHS,1,2899330.43,20201104,20201104,20241231,CA,...,,,,,,,,MD-2101|MD-1101,,
8,GH0010001,MD2233401513,6563,GHS,1,10000000.00,20220930,20220930,20230930,CA,...,,,,,,,,,,
9,GH0010001,MD2233401512,6563,GHS,1,10000000.00,20220930,20220930,20230930,CA,...,,,,,,,,,,
10,GH0010001,MD2134801345,330228,GHS,1,2930517.07,20210909,20210909,20241231,CA,...,,,,,,,,MD-2101|MD-1101,,
11,GH0010001,MD2224101476,909924,USD,1,4000000.00,20220809,20220809,20230831,CA,...,,,,,,,,MD-2101|MD-1101,,
12,GH0010001,MD2234801525,524309,GHS,1,1200000.00,20221130,20221130,20231129,CA,...,,,,,,,,MD-2101|MD-1101,,
13,GH0010001,MD2233401515,877627,GHS,1,20000000.00,20220930,20220930,20230930,CA,...,,,,,,,,,,
14,GH0010001,MD2317401559,33438,GHS,1,40886.00,20230529,20230529,20240528,CA,...,,,,,,,,,,
15,GH0010001,MD2232101485,346454,GHS,1,800000.00,20220930,20220930,20230930,CA,...,,,,,,,,MD-2101|MD-1101,,
16,GH0010001,MD2318001564,891364,GHS,1,100000.00,20230613,20230613,20240612,CA,...,,,,,,,,,,
17,GH0010001,MD2232201488,406553,GHS,1,300000.00,20220922,20220922,20230922,CA,...,,,,,,,,MD-2101|MD-1101,,
18,GH0010001,MD2206301397,313458,GHS,1,1526341.19,20220304,20220304,20241231,CA,...,,,,,,,,MD-2101|MD-1101,,
19,GH0010001,MD2233401502,7254,GHS,1,10000000.00,20220930,20220930,20230930,CA,...,,,,,,,,,,
20,GH0010001,MD2308101549,892096,GHS,1,40000.00,20230307,20230307,20230707,CA,...,,,,,,,,,,
21,GH0010001,MD2233401514,877627,GHS,1,10000000.00,20220930,20220930,20230930,CA,...,,,,,,,,,,
22,GH0010001,MD2232201487,431960,GHS,1,700000,20221117,20221117,20231117,CA,...,,,,,,,,MD-2101|MD-1101,,
23,GH0010001,MD2233401516,877627,GHS,1,20000000.00,20220930,20220930,20230930,CA,...,,,,,,,,,,
24,GH0010001,MD2317401560,125882,GHS,1,140000.00,20230512,20230512,20240511,CA,...,,,,,,,,,,
25,GH0010001,MD2233401495,6139,GHS,1,500000.00,20221108,20221108,20231108,CA,...,,,,,,,,MD-2101|MD-1101,,
26,GH0010001,MD2219601470,512340,USD,1,6000000.00,20220715,20220715,20230715,CA,...,,,,,,,,,,
27,GH0010001,MD2233401503,7254,GHS,1,10000000.00,20220930,20220930,20230930,CA,...,,,,,,,,,,
28,GH0010001,MD2002401039,37827,USD,1,2601792.17,20200108,20200108,20230915,CA,...,,,,,,,,,,
29,GH0010001,MD2233401507,264195,USD,1,50000.00,20221109,20221109,20231109,CA,...,,,,,,,,MD-2101|MD-1101,,
30,GH0010001,MD2130901322,330228,GHS,1,1278081.85,20201104,20201104,20241231,CA,...,,,,,,,,MD-2101|MD-1101,,
31,GH0010001,MD2212601436,395800,GHS,1,3500973.64,20220427,20220427,20230928,CA,...,,,,,,,,,,
32,GH0010001,MD2232201489,255467,GHS,1,1200000.00,20220815,20220815,20230815,CA,...,,,,,,,,MD-2101|MD-1101,,
33,GH0010001,MD2230601483,334011,GHS,1,1000000.00,20220822,20220822,20230923,CA,...,,,,,,,,MD-2101|MD-1101,,
34,GH0010001,MD2307901546,8062,GHS,1,200000.00,20221128,20221128,20231127,CA,...,,,,,,,,MD-2101|MD-1101,,
35,GH0010001,MD2309001552,114857,GHS,1,2778000.00,20230401,20230401,20240331,CA,...,,,,,,,,,,
36,GH0010001,MD2233501519,6563,GHS,1,10000000.00,20220930,20220930,20230930,CA,...,,,,,,,,,,
37,GH0010001,MD2233401511,6563,GHS,1,10000000.00,20220930,20220930,20230930,CA,...,,,,,,,,,,
38,GH0010001,MD2130901326,313458,GHS,1,3104225.04,20201104,20201104,20241231,CA,...,,,,,,,,MD-2101|MD-1101,,
39,GH0010001,MD2229201482,877563,USD,1,1220385.06,20221018,20221018,20231018,CA,...,,,,,,,,MD-2101|MD-1101,,
40,GH0010001,MD2318001563,891364,GHS,1,100000.00,20230613,20230613,20240612,CA,...,,,,,,,,,,

In [37]:
merged_columns_df.columns

Index(['UPLOAD_COMPANY_x', '@ID', 'CUSTOMER_x', 'CURRENCY_x', 'CCY_MARKET_x',
       'PRINCIPAL_AMOUNT_x', 'DEAL_DATE_x', 'VALUE_DATE_x', 'MATURITY_DATE_x',
       'CONTRACT_TYPE_x',
       ...
       'PROV_DR_ACCOUNT_z', 'SENDER_INFO_z', 'MATURITY_DATE_z',
       'LINK_REFERENCE_z', 'CHARGE_AMT_z', 'ADVICE_EXPIRY_DATE_z',
       'SL_PROD_TYPE_z', 'ACTIVITY_CODE_z', 'CONVERSION_RATE_z', 'CSN_DATE_z'],
      dtype='object', length=702)

In [38]:
# Create a list of columns to keep
columns_to_keep = [identifier] + [col for col in merged_columns_df.columns if col.endswith(("_z"))]

# Filter the DataFrame to keep only the desired columns
merged_columns_df = merged_columns_df.filter(columns_to_keep)

In [39]:
merged_columns_df

# # Drop columns ending with "_x" or "_y" except for "@ID"
# columns_to_drop = [col for col in common_rows.columns if col.endswith(("_x", "_y")) and col != "@ID"]
# common_rows = common_rows.drop(columns_to_drop, axis=1)

,@ID,REFERENCE_1_z,MD_SECTOR_z,UPLOAD_COMPANY_z,GTEE_DETAILS_z,EVENTS_PROCESSING_z,SETTLE_ACCOUNT_z,AUTO_EXPIRY_z,BENEF_CUST_1_z,LIMIT_UPD_REQD_z,...,PROV_DR_ACCOUNT_z,SENDER_INFO_z,MATURITY_DATE_z,LINK_REFERENCE_z,CHARGE_AMT_z,ADVICE_EXPIRY_DATE_z,SL_PROD_TYPE_z,ACTIVITY_CODE_z,CONVERSION_RATE_z,CSN_DATE_z
0,MD2219601468,,,,,,,,,,...,,,,,,,,MD-2101|MD-1101,,
1,MD2130901320,,,,,,,,,,...,,,,,,,,MD-2101|MD-1101,,
2,MD2233401509,,,,,,,,,,...,,,,,,,,,,
3,MD2234601523,,,,,,,,,,...,,,,,,,,MD-2101|MD-1101,,
4,MD2233401508,,,,,,,,,,...,,,,,,,,,,
5,MD2206301398,,,,,,,,,,...,,,,,,,,MD-2101|MD-1101,,
6,MD2318001562,,,,,,,,,,...,,,,,,,,,,
7,MD2130901325,,,,,,,,,,...,,,,,,,,MD-2101|MD-1101,,
8,MD2233401513,,,,,,,,,,...,,,,,,,,,,
9,MD2233401512,,,,,,,,,,...,,,,,,,,,,
10,MD2134801345,,,,,,,,,,...,,,,,,,,MD-2101|MD-1101,,
11,MD2224101476,,,,,,,,,,...,,,,,,,,MD-2101|MD-1101,,
12,MD2234801525,,,,,,,,,,...,,,,,,,,MD-2101|MD-1101,,
13,MD2233401515,,,,,,,,,,...,,,,,,,,,,
14,MD2317401559,,,,,,,,,,...,,,,,,,,,,
15,MD2232101485,,,,,,,,,,...,,,,,,,,MD-2101|MD-1101,,
16,MD2318001564,,,,,,,,,,...,,,,,,,,,,
17,MD2232201488,,,,,,,,,,...,,,,,,,,MD-2101|MD-1101,,
18,MD2206301397,,,,,,,,,,...,,,,,,,,MD-2101|MD-1101,,
19,MD2233401502,,,,,,,,,,...,,,,,,,,,,
20,MD2308101549,,,,,,,,,,...,,,,,,,,,,
21,MD2233401514,,,,,,,,,,...,,,,,,,,,,
22,MD2232201487,,,,,,,,,,...,,,,,,,,MD-2101|MD-1101,,
23,MD2233401516,,,,,,,,,,...,,,,,,,,,,
24,MD2317401560,,,,,,,,,,...,,,,,,,,,,
25,MD2233401495,,,,,,,,,,...,,,,,,,,MD-2101|MD-1101,,
26,MD2219601470,,,,,,,,,,...,,,,,,,,,,
27,MD2233401503,,,,,,,,,,...,,,,,,,,,,
28,MD2002401039,,,,,,,,,,...,,,,,,,,,,
29,MD2233401507,,,,,,,,,,...,,,,,,,,MD-2101|MD-1101,,
30,MD2130901322,,,,,,,,,,...,,,,,,,,MD-2101|MD-1101,,
31,MD2212601436,,,,,,,,,,...,,,,,,,,,,
32,MD2232201489,,,,,,,,,,...,,,,,,,,MD-2101|MD-1101,,
33,MD2230601483,,,,,,,,,,...,,,,,,,,MD-2101|MD-1101,,
34,MD2307901546,,,,,,,,,,...,,,,,,,,MD-2101|MD-1101,,
35,MD2309001552,,,,,,,,,,...,,,,,,,,,,
36,MD2233501519,,,,,,,,,,...,,,,,,,,,,
37,MD2233401511,,,,,,,,,,...,,,,,,,,,,
38,MD2130901326,,,,,,,,,,...,,,,,,,,MD-2101|MD-1101,,
39,MD2229201482,,,,,,,,,,...,,,,,,,,MD-2101|MD-1101,,
40,MD2318001563,,,,,,,,,,...,,,,,,,,,,

In [40]:
# common_rows

In [41]:
# List of columns in R22 data
r22_columns = r22_data.columns.tolist()

# List of columns in R14 data
r14_columns = r14_data.columns.tolist()

In [42]:
# Convert column names to sets for both DataFrames
r22_columns_set = set(r22_columns)
r14_columns_set = set(r14_columns)

# Find the common columns
common_columns = list(r22_columns_set.intersection(r14_columns_set))

# Find the columns that exist in r14 but not in r22
columns_only_in_r14 = list(r14_columns_set - r22_columns_set)

In [43]:
missing_ids = set(r14_data[identifier]) - set((merged_columns_df[identifier]))

In [45]:
# output_file_path = r"C:\Users\KATAKOF\Downloads\reconciled_data(try 8).xlsx"

# Create a DataFrame with the extra columns and missing IDs
extra_data_col = pd.DataFrame({ "Extra Columns": columns_only_in_r14 })
extra_data_id = pd.DataFrame({ "Missing in R22": list(missing_ids) })

# # Export df and extra_data to Excel file
# with pd.ExcelWriter(output_file_path) as writer:
#     merged_columns_df.to_excel(writer, sheet_name='Recon', index=False)
#     extra_data_col.to_excel(writer, sheet_name='Extra Columns', index=False)
#     extra_data_id.to_excel(writer, sheet_name='Missing Rows', index=False)

In [83]:
# Output file paths
csv_file_path = r"C:\Users\KATAKOF\Downloads\T24 DRESS REHEARSAL 2\Recon Output\MD.DEAL.EXT.csv"
extra_data_id_file_path = r"C:\Users\KATAKOF\Downloads\T24 DRESS REHEARSAL 2\Recon Output\missing_identifier(DR2.ACCOUNT).csv"
extra_data_col_file_path = r"C:\Users\KATAKOF\Downloads\T24 DRESS REHEARSAL 2\Recon Output\extra_columns(DR2.ACCOUNT).csv"


# Export merged_columns_df to CSV file
merged_columns_df.to_csv(csv_file_path, index=False)
extra_data_col.to_csv(extra_data_col_file_path, index=False)
extra_data_id.to_csv(extra_data_id_file_path, index=False)


# # Export extra_data_col to text file
# extra_data_col.to_csv(text_file_path, index=False, header=False, sep='\t')

# # Export extra_data_id to text file
# extra_data_id.to_csv(extra_data_id_file_path, mode='a', index=False, header=False, sep='\t')